version: '3.8'

services:
  aapanel:
    build: 
      context: ./bin/aapanel
    container_name: aapanel
    restart: unless-stopped
    ports:
      - "${AAPANEL_PORT}:7800"
      - "${WEBSERVER_HOST_PORT}:80"
      - "${WEBSERVER_SECURE_HOST_PORT}:443"
      - "${PHPMYADMIN_PORT}:888"
      - "${REDIS_PORT}:6379"
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${WEBSITE_LOG}:/www/wwwlogs
      - ${WEBSITE_VHOST}:/www/server/panel/vhost
      - ${WEBSITE_CRON}:/www/server/cron
      - ${WEBSITE_DATA}:/www/wwwroot
    environment:
      - TZ=Asia/Singapore
    env_file:
      - ./.env
 
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    restart: unless-stopped
    expose:
      - 9104
    ports:
      - 9104:9104
    depends_on:
      - aapanel
    volumes:
      - ./mysql-exporter/.mysqld_exporter.cnf:/root/.mysqld_exporter.cnf
    environment:
      - DATA_SOURCE_NAME=mysqld_exporter:5BSAvzaKmTttTUif@tcp(127.0.0.1:3306)/
    command:
      - '--mysqld.username=mysqld_exporter:5BSAvzaKmTttTUif'
      - '--mysqld.address=aapanel:3306'
      - '--collect.global_status'
      - '--collect.info_schema.innodb_metrics'
      - '--collect.auto_increment.columns'
      - '--collect.info_schema.processlist'
      - '--collect.binlog_size'
      - '--collect.info_schema.tablestats'
      - '--collect.global_variables'
      - '--collect.info_schema.query_response_time'
      - '--collect.info_schema.userstats'
      - '--collect.info_schema.tables'
      - '--collect.perf_schema.tablelocks'
      - '--collect.perf_schema.file_events'
      - '--collect.perf_schema.eventswaits'
      - '--collect.perf_schema.indexiowaits'
      - '--collect.perf_schema.tableiowaits'
      - '--collect.slave_status'
      - '--collect.info_schema.tables.databases=db-schema1'
      - '--collect.engine_innodb_status'
      - '--web.listen-address=0.0.0.0:9104'
    links:
      - aapanel

volumes:
  website_vhost:
  website_cron:
  website_data:
