version: '3.8'

services:
  aapanel:
    image: aapanel/aapanel
    container_name: aapanel
    restart: unless-stopped
    ports:
      - "${AAPANEL_PORT}:7800"
      - "${WEBSERVER_HOST_PORT}:80"
      - "${WEBSERVER_SECURE_HOST_PORT}:443"
      - "${PHPMYADMIN_PORT}:888"
      - "${REDIS_PORT}:6379"
      - "${MYSQL_PORT}:3306
    volumes:
      - aapanel_vhost:/www/server/panel/vhost
      - aapanel_mysql:/www/server/data
      - aapanel_wwwroot:/www/wwwroot
    environment:
      - TZ=Etc/UTC
    entrypoint: ["/entrypoint.sh"]
    env_file:
      - ./.env

volumes:
  aapanel_vhost:
    driver: local
    driver_opts:
      type: none
      device: /mnt/upcloud/aapanel_vhost
      o: bind
  aapanel_mysql:
    driver: local
    driver_opts:
      type: none
      device: /mnt/upcloud/aapanel_mysql
      o: bind
  aapanel_wwwroot:
    driver: local
    driver_opts:
      type: none
      device: /mnt/upcloud/aapanel_wwwroot
      o: bind
