version: '3.8'

services:
  aapanel:
    image: aapanel/aapanel
    container_name: aapanel
    ports:
      - "8888:8888"
    volumes:
      - aapanel_data:/www
      - aapanel_vhost:/www/server/panel/vhost
      - aapanel_mysql:/www/server/data
      - aapanel_wwwroot:/www/wwwroot
    environment:
      - TZ=Etc/UTC
    entrypoint: ["/entrypoint.sh"]
    depends_on:
      - rclone

  rclone:
    image: rclone/rclone
    command: mount upcloud:/bucket-name /mnt/upcloud --allow-other --vfs-cache-mode writes
    volumes:
      - rclone-config:/config/rclone
    environment:
      - RCLONE_CONFIG=/config/rclone/rclone.conf
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined

volumes:
  aapanel_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/upcloud/aapanel_data
      o: bind
  aapanel_vhost:
    driver: local
    driver_opts:
      type: none
      device: /mnt/upcloud/aapanel_vhost
      o: bind
  aapanel_mysql:
    driver: local
    driver_opts:
      type: none
      device: /mnt/upcloud/aapanel_mysql
      o: bind
  aapanel_wwwroot:
    driver: local
    driver_opts:
      type: none
      device: /mnt/upcloud/aapanel_wwwroot
      o: bind
  rclone-config:
    driver: local
    driver_opts:
      type: none
      device: /root/.config/rclone
      o: bind
